name: Java Program Build & Workflow Success/Failure Notification

on: push
    

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Debug file structure (for troubleshooting)
        run: |
          echo "Printing the file structure..."
          pwd  # Print working directory
          ls -la  # List files to confirm HelloWorld.java exists
      
      - name: Compile Java program
        run: |
          echo "Compiling the Java program..."
          javac HelloWorld.java

      - name: Run Java program
        run: |
          echo "Running the Java program..."
          java HelloWorld

  notify:
    runs-on: ubuntu-latest
    needs: java-build  # This makes sure `notify` runs after `java-build`
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Email notification
        run: |
          STATUS=$(if [[ $? -eq 0 ]]; then echo "success"; else echo "failure"; fi)
          SUBJECT="GitHub Workflow $STATUS"
          MESSAGE="The workflow has $STATUS. Please check the logs."
          
          if [[ "$STATUS" == "success" ]]; then
            MESSAGE="The Java program built and ran successfully, and the workflow completed successfully!"
          fi

          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
            https://api.mailgun.net/v3/${{ secrets.MAILGUN_DOMAIN }}/messages \
            -F from='noreply@${{ secrets.MAILGUN_DOMAIN }}' \
            -F to='rohan.walunjkar@avaloq.com' \
            -F subject="$SUBJECT" \
            -F text="$MESSAGE"
