name: Java Program Build & Workflow Success/Failure Notification

on: push
    

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'

      # - name: Debug file structure (for troubleshooting)
      #   run: |
      #     echo "Printing the file structure..."
      #     pwd  # Print working directory
      #     ls -la  # List files to confirm HelloWorld.java exists
      
      # - name: Compile Java program
      #   run: |
      #     echo "Compiling the Java program..."
      #     javac HelloWorld.java

      # - name: Run Java program
      #   run: |
      #     echo "Running the Java program..."
      #     java HelloWorld

      - name: java
        run: echo "Hello Rohan..."

    
    notify:
      runs-on: ubuntu-latest
      needs: java-build  # Ensure the Java build job runs before this
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Send Microsoft Teams Notification
          run: |
            # Check if the previous job (java-build) was successful
            STATUS=$(if [[ $? -eq 0 ]]; then echo "success"; else echo "failure"; fi)
            MESSAGE="The workflow has $STATUS. Please check the logs."
            
            if [[ "$STATUS" == "success" ]]; then
              MESSAGE="The Java program built and ran successfully, and the workflow completed successfully!"
            fi

            # Send the message to Microsoft Teams using the Webhook URL
            curl -X POST \
              -H 'Content-Type: application/json' \
              --data '{
                "@type": "MessageCard",
                "@context": "http://schema.org/extensions",
                "themeColor": "0076D7",
                "summary": "GitHub Workflow Notification",
                "sections": [{
                  "activityTitle": "GitHub Workflow Notification",
                  "activitySubtitle": "'"$STATUS"'",
                  "text": "'"$MESSAGE"'"
                }]
              }' \
              ${{ secrets.TEAMS_WEBHOOK_URL }}  # Correctly reference the GitHub secret




  # notify:
  #   runs-on: ubuntu-latest
  #   needs: java-build  # Ensure the Java build job runs before this
    
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Send Microsoft Teams Notification
  #       run: |
  #         STATUS=$(if [[ $? -eq 0 ]]; then echo "success"; else echo "failure"; fi)
  #         MESSAGE="The workflow has $STATUS. Please check the logs."
          
  #         if [[ "$STATUS" == "success" ]]; then
  #           MESSAGE="The Java program built and ran successfully, and the workflow completed successfully!"
  #         fi

  #         # Microsoft Teams Incoming Webhook format
  #         curl -X POST \
  #           -H 'Content-Type: application/json' \
  #           --data '{
  #             "@type": "MessageCard",
  #             "@context": "http://schema.org/extensions",
  #             "themeColor": "0076D7",
  #             "summary": "GitHub Workflow Notification",
  #             "sections": [{
  #               "activityTitle": "GitHub Workflow Notification",
  #               "activitySubtitle": "'"$STATUS"'",
  #               "text": "'"$MESSAGE"'"
  #             }]
  #           }' \
  #           ${{ secrets.TEAMS_WEBHOOK_URL }}
